# Generated by Django 3.2.7 on 2022-10-31 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0004_remove_post_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='reply',
            field=models.ManyToManyField(null=True, related_name='replies', to='blog_app.Response'),
        ),
    ]
