# Generated by Django 3.2.7 on 2022-11-01 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0005_post_reply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='reply',
        ),
        migrations.AddField(
            model_name='response',
            name='reply',
            field=models.ManyToManyField(null=True, related_name='replies', to='blog_app.Post'),
        ),
        migrations.AlterField(
            model_name='response',
            name='responder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responders', to='blog_app.user'),
        ),
    ]
