# Generated by Django 3.2.7 on 2023-03-03 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0006_auto_20221101_0416'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='response',
            name='reply',
        ),
        migrations.AddField(
            model_name='response',
            name='reply',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='blog_app.post'),
        ),
    ]
