# Generated by Django 3.2.7 on 2023-03-04 02:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0008_auto_20230304_0216'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='reply',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='blog_app.post'),
        ),
        migrations.AlterField(
            model_name='response',
            name='text',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
