# Generated by Django 3.2.7 on 2023-08-07 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0009_auto_20230304_0221'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog_app.post'),
        ),
        migrations.AlterField(
            model_name='response',
            name='responder',
            field=models.CharField(max_length=255),
        ),
    ]
